### PR TITLE
Java 15.0.2+10 for Linux

### PR DESCRIPTION
**Pull request by panther7**
- add jre for linux
- change hash to sha1

#21

### CODE REVIEW

**Comment by rednoah** [comment]
Sorry, but `get-java.sh` is auto-generated so we don't accept changes here. Additionally, `SHA256` is the industry standard, so downgrading to `SHA1` is not planned.

**Comment by panther7** [comment]
@rednoah Ok, Is possible add jre to generator script?

**Comment by rednoah** [comment]
`jre` binaries are no longer maintained, since `jlink` takes care of generating minimized application-specific JRE bundles nowadays.

**Comment by panther7** [comment]
Not maintained? I using JRE normaly ... But, always i need add these lines to script.

`` `
         "Linux aarch64 is")
                 JDK_URL = "https://download.bell-sw.com/java/16.0.1+9/bellsoft-jre16.0.1+9-linux-aarch64.tar.gz"
                 JDK_SHA256 = "cdb1da7d98ce4c71ff90fa09ce53a45a82e69ccc06386182f675e58edc865346"
         ;;
`` `

I don't see, why not added theese lines to autogenerator ...

**Comment by rednoah** [comment]
Sorry, my use case is different from yours, so I don't plan on adding features that I myself have no need for. You're welcome to create your own fork. Adding support for `jre` builds in the generator shouldn't be too hard:
https://github.com/rednoah/java-installer/blob/latest/build-jdk.groovy#L10

**Comment by panther7** [comment]
Ok, I make own fork, but, could you help with how build qnap (qpkg) package? In your repo missing build readme.

**Comment by rednoah** [comment]
`make pkg` will build the SPK and QPKG package.

**Comment by panther7** [comment]
After hard work (Install docker, ant, ivy on Windows...), done

#24 add JRE support with generator script...

If you want.

**Pull request closed without merging**
