### PR TITLE
Fix icons for QNAP

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Comment by rednoah** [comment]
Why fix something that isn't broken? Your browser will happily display `PNG images` even if they're named with `<package name>.gif` for QTS for compatibility / historical reasons.

**Comment by panther7** [comment]
md5 mismatch, after call `ant qnap`, my pull request fixing it ...

**Comment by rednoah** [comment]
Well, I wouldn't wanna brush off well-intended bug reports, but I guess in this case I can only say "cannot reproduce the problem" in this case and leave it at that.

**Comment by rednoah** [comment]
https://github.com/rednoah/java-installer/commit/09bd7e98565403161d99234b8f0ba6ebe2a9f9ce fixes potential issues that would arise if we were to use `*.gif` files.

**Pull request closed without merging**
